name = "SIEGE"
uuid = "1872db6e-75b1-436b-ac68-765da848f08b"
authors = ["Ashlin Harris <ashlin_harris@brown.edu>"]
version = "0.4.1"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "^1.8"

